server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://60.205.254.33:3306/test01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: test01
    password: pDSpzHeDYeA6hiGD

mybatis:
  type-aliases-package: com.bcqh.springcloud.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-provider-payment-8001

