server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yezhangqing/springcloudconfig.git
          search-paths:
            - springcloudconfig
      label: master
  rabbitmq:
    host: 60.205.254.33
    port: 5672
    username: user
    password: 123456
    virtual-host: /bcqh


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

