server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yezhangqing/springcloudconfig.git
          search-paths:
            - springcloudconfig
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
