server:
  port: 8080

spring:
  application:
    name: cloud-consumer-order-80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
